url: https://stockholm.ai

# Site settings
title: Stockholm.AI
email: info@stockholm.ai
description: "Stockholm.AI is a non-profit organization with the goal to improve the AI community in Stockholm"

organization:
    name: Stockholm.AI
    webadmin:
        mail: info@stockholm.ai


# Team names, titles and social links
people:
- name: Ricky Helgesson
  pic: ricky-helgesson.jpg
  position: CEO at Univrses
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/rickyhelgesson/ 
    - title: twitter
      url: https://twitter.com/rickyhelgesson 

- name: Magnus Nordin
  pic: magnus-nordin.jpg
  position: Technical Director, SEED / EA
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/magnus-nordin-10393b1/
    - title: twitter
      url: https://twitter.com/magnord

- name: Oskar Juhlin
  pic: oskar-juhlin.jpg
  position: Professor at Stockholm University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/oskar-juhlin-43a102/
    - title: twitter
      url: https://twitter.com/oskarju


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sthlmai
  - title: facebook
    url: https://www.facebook.com/groups/stockholmai
  - title: github
    url: http://github.com/Stockholm-AI
  - title: meetup
    url: https://www.meetup.com/StockholmAI
  - title: linkedin
    url: https://www.linkedin.com/company/stockholm.ai
#  - title: crunchbase
#    url: https://www.crunchbase.com/organization/stockholm-ai

# Postal address (add as many lines as necessary)
address:
  - line: Artillerigatan 87 LGH 1006
  - line: 115 30 Stockholm

# Build settings
markdown: kramdown
permalink: /:categories/:title
