url: https://stockholm.ai

collections:
  people:
    output: true
    permalink: /:collection/:title
  meetups:
    output: true
    permalink: /:collection/:title

# collections_dir: collections

defaults:
  - scope:
      path: ""
      type: people
    values:
      layout: people

# Build settings
markdown: kramdown
permalink: /:categories/:title
